/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_foyer_agent (void)
{
  GtkWidget *foyer_agent;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *entryADD_STUDENT_FIRSTNAME;
  GtkWidget *entryADD_STUDENT_MAIL;
  GtkWidget *entryADD_STUDENT_ID;
  GtkWidget *entryADD_STUDENT_LASTNAME;
  GtkObject *spinbuttonADD_STUDENT_DAY_adj;
  GtkWidget *spinbuttonADD_STUDENT_DAY;
  GtkObject *spinbuttonADD_STUDENT_YEAR_adj;
  GtkWidget *spinbuttonADD_STUDENT_YEAR;
  GtkObject *spinbuttonADD_STUDENT_MONTH_adj;
  GtkWidget *spinbuttonADD_STUDENT_MONTH;
  GtkWidget *label13;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkObject *spinbuttonADD_STUDENT_FLOOR_adj;
  GtkWidget *spinbuttonADD_STUDENT_FLOOR;
  GtkWidget *label64;
  GtkWidget *entryADD_STUDENT_CHAMBER;
  GtkWidget *label62;
  GtkWidget *label12;
  GtkWidget *label71;
  GtkWidget *comboboxentryADD_STUDENT_BLOC;
  GtkWidget *buttonADD_STUDENT;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label14;
  GtkWidget *buttonDISPLAY_STUDENT;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label15;
  GtkWidget *labelADD_MSG;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *entrySTUDENT_ID;
  GtkWidget *label18;
  GtkWidget *buttonREMOVE_STUDENT;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label19;
  GtkWidget *button1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *labelREMOVE_MSG;
  GtkWidget *label3;
  GtkWidget *fixed5;
  GtkWidget *entryUPDATE_ID_UPDATE;
  GtkWidget *label20;
  GtkWidget *vseparator1;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *labelID;
  GtkWidget *fixed7;
  GtkWidget *entryUPDATE_FIRST_NAME;
  GtkWidget *entryUPDATE_MAIL;
  GtkWidget *entryUPDATE_ID;
  GtkWidget *entryUPDATE_LAST_NAME;
  GtkObject *spinbuttonUPDATE_DAY_adj;
  GtkWidget *spinbuttonUPDATE_DAY;
  GtkWidget *label36;
  GtkObject *spinbuttonUPDATE_YEAR_adj;
  GtkWidget *spinbuttonUPDATE_YEAR;
  GtkObject *spinbuttonUPDATE_MONTH_adj;
  GtkWidget *spinbuttonUPDATE_MONTH;
  GtkWidget *label37;
  GtkWidget *label41;
  GtkWidget *label35;
  GtkWidget *label40;
  GtkWidget *label34;
  GtkWidget *labelFIRSTNAME;
  GtkWidget *buttonSHOW_UPDATE;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label42;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkObject *spinbuttonUPDATE_FLOOR_adj;
  GtkWidget *spinbuttonUPDATE_FLOOR;
  GtkWidget *label72;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label73;
  GtkWidget *entryUPDATE_CHAMBER;
  GtkWidget *label47;
  GtkWidget *labelFLOOR;
  GtkWidget *labelCHAMBER;
  GtkWidget *labelMAIL;
  GtkWidget *labelBIRTHDAY;
  GtkWidget *labelBLOC;
  GtkWidget *comboboxentryUPDATE_BLOC;
  GtkWidget *labelLASTNAME;
  GtkWidget *button_START_UPDATING_STUDENT;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label25;
  GtkWidget *button2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;
  GtkWidget *labelUPDATE_MSG;
  GtkWidget *label4;
  GtkWidget *fixed8;
  GtkWidget *entryFIND_ID;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label51;
  GtkWidget *labelID1;
  GtkWidget *label48;
  GtkWidget *label74;
  GtkWidget *label70;
  GtkWidget *label69;
  GtkWidget *label55;
  GtkWidget *labelBIRTHDAY1;
  GtkWidget *labelMAIL1;
  GtkWidget *labelCHAMBER1;
  GtkWidget *labelLASTNAME1;
  GtkWidget *labelBLOC1;
  GtkWidget *labelFLOOR1;
  GtkWidget *labelFIRSTNAME1;
  GtkWidget *buttonFIND;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label61;
  GtkWidget *FIND;
  GtkWidget *fixed9;
  GtkObject *spinbuttonFLOOR_TASK_BREAKDOWN_adj;
  GtkWidget *spinbuttonFLOOR_TASK_BREAKDOWN;
  GtkWidget *label79;
  GtkWidget *label77;
  GtkWidget *labelSTUDENT_NUMBER;
  GtkWidget *labelBLOC_NUMBER;
  GtkWidget *labelFLOOR_NUMBER;
  GtkWidget *comboboxentryBLOC_TASK_BREAKDOWN;
  GtkWidget *label88;
  GtkWidget *label75;
  GtkWidget *buttonSHOW_BLOC;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label86;
  GtkWidget *buttonSHOW_FLOOR;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label85;
  GtkWidget *buttonSHOW_STUDENT;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label83;
  GtkWidget *entryCHAMBER_TASK_BREAKDOWN;
  GtkWidget *label81;
  GtkWidget *buttonSHOW_CHAMBER;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label87;
  GtkWidget *labelCHAMBER_NUMBER;
  GtkWidget *label6;
  GtkWidget *label1;

  foyer_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (foyer_agent), _("foyer agent"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (foyer_agent), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 56);
  gtk_widget_set_size_request (notebook1, 624, 664);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entryADD_STUDENT_FIRSTNAME = gtk_entry_new ();
  gtk_widget_show (entryADD_STUDENT_FIRSTNAME);
  gtk_fixed_put (GTK_FIXED (fixed2), entryADD_STUDENT_FIRSTNAME, 232, 64);
  gtk_widget_set_size_request (entryADD_STUDENT_FIRSTNAME, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryADD_STUDENT_FIRSTNAME), 8226);

  entryADD_STUDENT_MAIL = gtk_entry_new ();
  gtk_widget_show (entryADD_STUDENT_MAIL);
  gtk_fixed_put (GTK_FIXED (fixed2), entryADD_STUDENT_MAIL, 232, 280);
  gtk_widget_set_size_request (entryADD_STUDENT_MAIL, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryADD_STUDENT_MAIL), 8226);

  entryADD_STUDENT_ID = gtk_entry_new ();
  gtk_widget_show (entryADD_STUDENT_ID);
  gtk_fixed_put (GTK_FIXED (fixed2), entryADD_STUDENT_ID, 232, 160);
  gtk_widget_set_size_request (entryADD_STUDENT_ID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryADD_STUDENT_ID), 8226);

  entryADD_STUDENT_LASTNAME = gtk_entry_new ();
  gtk_widget_show (entryADD_STUDENT_LASTNAME);
  gtk_fixed_put (GTK_FIXED (fixed2), entryADD_STUDENT_LASTNAME, 232, 112);
  gtk_widget_set_size_request (entryADD_STUDENT_LASTNAME, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryADD_STUDENT_LASTNAME), 8226);

  spinbuttonADD_STUDENT_DAY_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonADD_STUDENT_DAY = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonADD_STUDENT_DAY_adj), 1, 0);
  gtk_widget_show (spinbuttonADD_STUDENT_DAY);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonADD_STUDENT_DAY, 232, 208);
  gtk_widget_set_size_request (spinbuttonADD_STUDENT_DAY, 60, 27);

  spinbuttonADD_STUDENT_YEAR_adj = gtk_adjustment_new (1999, 1990, 2010, 1, 10, 10);
  spinbuttonADD_STUDENT_YEAR = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonADD_STUDENT_YEAR_adj), 1, 0);
  gtk_widget_show (spinbuttonADD_STUDENT_YEAR);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonADD_STUDENT_YEAR, 376, 208);
  gtk_widget_set_size_request (spinbuttonADD_STUDENT_YEAR, 60, 27);

  spinbuttonADD_STUDENT_MONTH_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonADD_STUDENT_MONTH = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonADD_STUDENT_MONTH_adj), 1, 0);
  gtk_widget_show (spinbuttonADD_STUDENT_MONTH);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonADD_STUDENT_MONTH, 304, 208);
  gtk_widget_set_size_request (spinbuttonADD_STUDENT_MONTH, 60, 27);

  label13 = gtk_label_new (_("(DD /MM/YY)"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 200, 248);
  gtk_widget_set_size_request (label13, 272, 17);

  label10 = gtk_label_new (_("FIRST NAME  :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 96, 64);
  gtk_widget_set_size_request (label10, 129, 24);

  label8 = gtk_label_new (_("LAST NAME  :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 96, 112);
  gtk_widget_set_size_request (label8, 129, 24);

  label9 = gtk_label_new (_("ID :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 96, 160);
  gtk_widget_set_size_request (label9, 129, 24);

  label11 = gtk_label_new (_("BIRTHDAY  :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 96, 208);
  gtk_widget_set_size_request (label11, 129, 24);

  spinbuttonADD_STUDENT_FLOOR_adj = gtk_adjustment_new (1, 0, 4, 1, 10, 10);
  spinbuttonADD_STUDENT_FLOOR = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonADD_STUDENT_FLOOR_adj), 1, 0);
  gtk_widget_show (spinbuttonADD_STUDENT_FLOOR);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonADD_STUDENT_FLOOR, 232, 408);
  gtk_widget_set_size_request (spinbuttonADD_STUDENT_FLOOR, 60, 27);

  label64 = gtk_label_new (_("FLOOR NUMBER :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed2), label64, 72, 416);
  gtk_widget_set_size_request (label64, 125, 17);

  entryADD_STUDENT_CHAMBER = gtk_entry_new ();
  gtk_widget_show (entryADD_STUDENT_CHAMBER);
  gtk_fixed_put (GTK_FIXED (fixed2), entryADD_STUDENT_CHAMBER, 224, 472);
  gtk_widget_set_size_request (entryADD_STUDENT_CHAMBER, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryADD_STUDENT_CHAMBER), 8226);

  label62 = gtk_label_new (_("BLOC :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed2), label62, 104, 352);
  gtk_widget_set_size_request (label62, 90, 17);

  label12 = gtk_label_new (_("MAIL  :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 96, 280);
  gtk_widget_set_size_request (label12, 129, 24);

  label71 = gtk_label_new (_("CHAMBER NUMBER :"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed2), label71, 64, 480);
  gtk_widget_set_size_request (label71, 140, 17);

  comboboxentryADD_STUDENT_BLOC = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryADD_STUDENT_BLOC);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentryADD_STUDENT_BLOC, 224, 344);
  gtk_widget_set_size_request (comboboxentryADD_STUDENT_BLOC, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryADD_STUDENT_BLOC), _("EXTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryADD_STUDENT_BLOC), _("EXTERIOR-B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryADD_STUDENT_BLOC), _("INTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryADD_STUDENT_BLOC), _("INTERIOR-B"));

  buttonADD_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonADD_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonADD_STUDENT, 120, 568);
  gtk_widget_set_size_request (buttonADD_STUDENT, 110, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonADD_STUDENT), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("ADD"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox1), label14, FALSE, FALSE, 0);

  buttonDISPLAY_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonDISPLAY_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonDISPLAY_STUDENT, 360, 568);
  gtk_widget_set_size_request (buttonDISPLAY_STUDENT, 110, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonDISPLAY_STUDENT), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox2), label15, FALSE, FALSE, 0);

  labelADD_MSG = gtk_label_new ("");
  gtk_widget_show (labelADD_MSG);
  gtk_fixed_put (GTK_FIXED (fixed2), labelADD_MSG, 144, 536);
  gtk_widget_set_size_request (labelADD_MSG, 300, 17);

  label2 = gtk_label_new (_("ADD"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);
  gtk_widget_set_size_request (label2, 94, -1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entrySTUDENT_ID = gtk_entry_new ();
  gtk_widget_show (entrySTUDENT_ID);
  gtk_fixed_put (GTK_FIXED (fixed4), entrySTUDENT_ID, 192, 104);
  gtk_widget_set_size_request (entrySTUDENT_ID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySTUDENT_ID), 8226);

  label18 = gtk_label_new (_("ID"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 40, 112);
  gtk_widget_set_size_request (label18, 200, 17);

  buttonREMOVE_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonREMOVE_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonREMOVE_STUDENT, 96, 264);
  gtk_widget_set_size_request (buttonREMOVE_STUDENT, 100, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonREMOVE_STUDENT), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("REMOVE"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox5), label19, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed4), button1, 344, 264);
  gtk_widget_set_size_request (button1, 110, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  labelREMOVE_MSG = gtk_label_new ("");
  gtk_widget_show (labelREMOVE_MSG);
  gtk_fixed_put (GTK_FIXED (fixed4), labelREMOVE_MSG, 112, 200);
  gtk_widget_set_size_request (labelREMOVE_MSG, 300, 17);

  label3 = gtk_label_new (_("REMOVE"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);
  gtk_widget_set_size_request (label3, 90, -1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entryUPDATE_ID_UPDATE = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_ID_UPDATE);
  gtk_fixed_put (GTK_FIXED (fixed5), entryUPDATE_ID_UPDATE, 64, 40);
  gtk_widget_set_size_request (entryUPDATE_ID_UPDATE, 128, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_ID_UPDATE), 8226);

  label20 = gtk_label_new (_("ID "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 8, 40);
  gtk_widget_set_size_request (label20, 64, 24);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), vseparator1, 184, 0);
  gtk_widget_set_size_request (vseparator1, 96, 320);

  label43 = gtk_label_new (_("FIRST NAME  :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 0, 176);
  gtk_widget_set_size_request (label43, 129, 24);

  label44 = gtk_label_new (_("LAST NAME  :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 0, 224);
  gtk_widget_set_size_request (label44, 129, 24);

  label45 = gtk_label_new (_("ID :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed5), label45, 0, 280);
  gtk_widget_set_size_request (label45, 129, 24);

  label46 = gtk_label_new (_("BIRTHDAY  :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed5), label46, 0, 336);
  gtk_widget_set_size_request (label46, 129, 24);

  labelID = gtk_label_new ("");
  gtk_widget_show (labelID);
  gtk_fixed_put (GTK_FIXED (fixed5), labelID, 112, 280);
  gtk_widget_set_size_request (labelID, 112, 24);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed7, 160, 0);
  gtk_widget_set_size_request (fixed7, 120, 80);

  entryUPDATE_FIRST_NAME = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_FIRST_NAME);
  gtk_fixed_put (GTK_FIXED (fixed7), entryUPDATE_FIRST_NAME, 232, 64);
  gtk_widget_set_size_request (entryUPDATE_FIRST_NAME, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_FIRST_NAME), 8226);

  entryUPDATE_MAIL = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_MAIL);
  gtk_fixed_put (GTK_FIXED (fixed7), entryUPDATE_MAIL, 232, 280);
  gtk_widget_set_size_request (entryUPDATE_MAIL, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_MAIL), 8226);

  entryUPDATE_ID = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_ID);
  gtk_fixed_put (GTK_FIXED (fixed7), entryUPDATE_ID, 232, 160);
  gtk_widget_set_size_request (entryUPDATE_ID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_ID), 8226);

  entryUPDATE_LAST_NAME = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_LAST_NAME);
  gtk_fixed_put (GTK_FIXED (fixed7), entryUPDATE_LAST_NAME, 232, 112);
  gtk_widget_set_size_request (entryUPDATE_LAST_NAME, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_LAST_NAME), 8226);

  spinbuttonUPDATE_DAY_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonUPDATE_DAY = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_DAY_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_DAY);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonUPDATE_DAY, 232, 208);
  gtk_widget_set_size_request (spinbuttonUPDATE_DAY, 60, 27);

  label36 = gtk_label_new (_("MAIL  :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 96, 280);
  gtk_widget_set_size_request (label36, 129, 24);

  spinbuttonUPDATE_YEAR_adj = gtk_adjustment_new (1999, 1990, 2010, 1, 10, 10);
  spinbuttonUPDATE_YEAR = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_YEAR_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_YEAR);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonUPDATE_YEAR, 384, 208);
  gtk_widget_set_size_request (spinbuttonUPDATE_YEAR, 60, 27);

  spinbuttonUPDATE_MONTH_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonUPDATE_MONTH = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_MONTH_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_MONTH);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonUPDATE_MONTH, 304, 208);
  gtk_widget_set_size_request (spinbuttonUPDATE_MONTH, 60, 27);

  label37 = gtk_label_new (_("(DD /MM/YY)"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 200, 248);
  gtk_widget_set_size_request (label37, 272, 17);

  label41 = gtk_label_new (_("LAST NAME  :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 96, 112);
  gtk_widget_set_size_request (label41, 129, 24);

  label35 = gtk_label_new (_("BIRTHDAY  :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed7), label35, 104, 208);
  gtk_widget_set_size_request (label35, 129, 24);

  label40 = gtk_label_new (_("FIRST NAME  :"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 96, 64);
  gtk_widget_set_size_request (label40, 129, 24);

  label34 = gtk_label_new (_("ID :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 96, 160);
  gtk_widget_set_size_request (label34, 129, 24);

  labelFIRSTNAME = gtk_label_new ("");
  gtk_widget_show (labelFIRSTNAME);
  gtk_fixed_put (GTK_FIXED (fixed5), labelFIRSTNAME, 112, 176);
  gtk_widget_set_size_request (labelFIRSTNAME, 112, 24);

  buttonSHOW_UPDATE = gtk_button_new ();
  gtk_widget_show (buttonSHOW_UPDATE);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonSHOW_UPDATE, 56, 96);
  gtk_widget_set_size_request (buttonSHOW_UPDATE, 110, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_UPDATE), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("SHOW"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox12), label42, FALSE, FALSE, 0);

  label65 = gtk_label_new (_("BLOC :"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed5), label65, 16, 448);
  gtk_widget_set_size_request (label65, 90, 17);

  label66 = gtk_label_new (_("BLOC :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed5), label66, 272, 344);
  gtk_widget_set_size_request (label66, 90, 17);

  spinbuttonUPDATE_FLOOR_adj = gtk_adjustment_new (1, 0, 4, 1, 10, 10);
  spinbuttonUPDATE_FLOOR = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_FLOOR_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_FLOOR);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbuttonUPDATE_FLOOR, 400, 384);
  gtk_widget_set_size_request (spinbuttonUPDATE_FLOOR, 60, 27);

  label72 = gtk_label_new (_("CHAMBER NUMBER :"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed5), label72, 0, 560);
  gtk_widget_set_size_request (label72, 140, 17);

  label67 = gtk_label_new (_("FLOOR NUMBER :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed5), label67, 0, 504);
  gtk_widget_set_size_request (label67, 125, 17);

  label68 = gtk_label_new (_("FLOOR NUMBER :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed5), label68, 256, 392);
  gtk_widget_set_size_request (label68, 125, 17);

  label73 = gtk_label_new (_("CHAMBER NUMBER :"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed5), label73, 256, 440);
  gtk_widget_set_size_request (label73, 140, 17);

  entryUPDATE_CHAMBER = gtk_entry_new ();
  gtk_widget_show (entryUPDATE_CHAMBER);
  gtk_fixed_put (GTK_FIXED (fixed5), entryUPDATE_CHAMBER, 408, 432);
  gtk_widget_set_size_request (entryUPDATE_CHAMBER, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUPDATE_CHAMBER), 8226);

  label47 = gtk_label_new (_("MAIL  :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed5), label47, 0, 392);
  gtk_widget_set_size_request (label47, 129, 24);

  labelFLOOR = gtk_label_new ("");
  gtk_widget_show (labelFLOOR);
  gtk_fixed_put (GTK_FIXED (fixed5), labelFLOOR, 144, 504);
  gtk_widget_set_size_request (labelFLOOR, 80, 17);

  labelCHAMBER = gtk_label_new ("");
  gtk_widget_show (labelCHAMBER);
  gtk_fixed_put (GTK_FIXED (fixed5), labelCHAMBER, 168, 560);
  gtk_widget_set_size_request (labelCHAMBER, 80, 17);

  labelMAIL = gtk_label_new ("");
  gtk_widget_show (labelMAIL);
  gtk_fixed_put (GTK_FIXED (fixed5), labelMAIL, 112, 392);
  gtk_widget_set_size_request (labelMAIL, 112, 24);

  labelBIRTHDAY = gtk_label_new ("");
  gtk_widget_show (labelBIRTHDAY);
  gtk_fixed_put (GTK_FIXED (fixed5), labelBIRTHDAY, 112, 336);
  gtk_widget_set_size_request (labelBIRTHDAY, 112, 24);

  labelBLOC = gtk_label_new ("");
  gtk_widget_show (labelBLOC);
  gtk_fixed_put (GTK_FIXED (fixed5), labelBLOC, 136, 448);
  gtk_widget_set_size_request (labelBLOC, 80, 17);

  comboboxentryUPDATE_BLOC = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryUPDATE_BLOC);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentryUPDATE_BLOC, 384, 336);
  gtk_widget_set_size_request (comboboxentryUPDATE_BLOC, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryUPDATE_BLOC), _("EXTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryUPDATE_BLOC), _("EXTERIOR-B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryUPDATE_BLOC), _("INTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryUPDATE_BLOC), _("INTERIOR-B"));

  labelLASTNAME = gtk_label_new ("");
  gtk_widget_show (labelLASTNAME);
  gtk_fixed_put (GTK_FIXED (fixed5), labelLASTNAME, 112, 224);
  gtk_widget_set_size_request (labelLASTNAME, 112, 24);

  button_START_UPDATING_STUDENT = gtk_button_new ();
  gtk_widget_show (button_START_UPDATING_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed5), button_START_UPDATING_STUDENT, 280, 560);
  gtk_widget_set_size_request (button_START_UPDATING_STUDENT, 110, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_START_UPDATING_STUDENT), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("UPDATE"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed5), button2, 456, 560);
  gtk_widget_set_size_request (button2, 110, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  labelUPDATE_MSG = gtk_label_new ("");
  gtk_widget_show (labelUPDATE_MSG);
  gtk_fixed_put (GTK_FIXED (fixed5), labelUPDATE_MSG, 256, 504);
  gtk_widget_set_size_request (labelUPDATE_MSG, 300, 17);

  label4 = gtk_label_new (_("UPDATE"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label4);
  gtk_widget_set_size_request (label4, 120, -1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entryFIND_ID = gtk_entry_new ();
  gtk_widget_show (entryFIND_ID);
  gtk_fixed_put (GTK_FIXED (fixed8), entryFIND_ID, 64, 40);
  gtk_widget_set_size_request (entryFIND_ID, 128, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryFIND_ID), 8226);

  label52 = gtk_label_new (_("LAST NAME  :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed8), label52, 80, 160);
  gtk_widget_set_size_request (label52, 129, 24);

  label53 = gtk_label_new (_("ID :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed8), label53, 72, 208);
  gtk_widget_set_size_request (label53, 129, 24);

  label54 = gtk_label_new (_("BIRTHDAY  :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed8), label54, 72, 248);
  gtk_widget_set_size_request (label54, 129, 24);

  label51 = gtk_label_new (_("FIRST NAME  :"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed8), label51, 80, 120);
  gtk_widget_set_size_request (label51, 129, 24);

  labelID1 = gtk_label_new ("");
  gtk_widget_show (labelID1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelID1, 216, 208);
  gtk_widget_set_size_request (labelID1, 112, 24);

  label48 = gtk_label_new (_("ID "));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed8), label48, 8, 40);
  gtk_widget_set_size_request (label48, 64, 24);

  label74 = gtk_label_new (_("CHAMBER NUMBER :"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed8), label74, 64, 480);
  gtk_widget_set_size_request (label74, 140, 17);

  label70 = gtk_label_new (_("FLOOR NUMBER :"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed8), label70, 72, 416);
  gtk_widget_set_size_request (label70, 125, 17);

  label69 = gtk_label_new (_("BLOC :"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed8), label69, 104, 352);
  gtk_widget_set_size_request (label69, 90, 17);

  label55 = gtk_label_new (_("MAIL  :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed8), label55, 80, 296);
  gtk_widget_set_size_request (label55, 129, 24);

  labelBIRTHDAY1 = gtk_label_new ("");
  gtk_widget_show (labelBIRTHDAY1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelBIRTHDAY1, 224, 248);
  gtk_widget_set_size_request (labelBIRTHDAY1, 112, 24);

  labelMAIL1 = gtk_label_new ("");
  gtk_widget_show (labelMAIL1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelMAIL1, 224, 296);
  gtk_widget_set_size_request (labelMAIL1, 112, 24);

  labelCHAMBER1 = gtk_label_new ("");
  gtk_widget_show (labelCHAMBER1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelCHAMBER1, 240, 480);
  gtk_widget_set_size_request (labelCHAMBER1, 80, 17);

  labelLASTNAME1 = gtk_label_new ("");
  gtk_widget_show (labelLASTNAME1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelLASTNAME1, 216, 160);
  gtk_widget_set_size_request (labelLASTNAME1, 112, 24);

  labelBLOC1 = gtk_label_new ("");
  gtk_widget_show (labelBLOC1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelBLOC1, 232, 352);
  gtk_widget_set_size_request (labelBLOC1, 80, 17);

  labelFLOOR1 = gtk_label_new ("");
  gtk_widget_show (labelFLOOR1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelFLOOR1, 232, 416);
  gtk_widget_set_size_request (labelFLOOR1, 80, 17);

  labelFIRSTNAME1 = gtk_label_new ("");
  gtk_widget_show (labelFIRSTNAME1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelFIRSTNAME1, 216, 120);
  gtk_widget_set_size_request (labelFIRSTNAME1, 112, 24);

  buttonFIND = gtk_button_new ();
  gtk_widget_show (buttonFIND);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonFIND, 288, 40);
  gtk_widget_set_size_request (buttonFIND, 110, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonFIND), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("FIND"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox15), label61, FALSE, FALSE, 0);

  FIND = gtk_label_new (_("FIND"));
  gtk_widget_show (FIND);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), FIND);
  gtk_widget_set_size_request (FIND, 120, -1);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  spinbuttonFLOOR_TASK_BREAKDOWN_adj = gtk_adjustment_new (1, 0, 4, 1, 10, 10);
  spinbuttonFLOOR_TASK_BREAKDOWN = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonFLOOR_TASK_BREAKDOWN_adj), 1, 0);
  gtk_widget_show (spinbuttonFLOOR_TASK_BREAKDOWN);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonFLOOR_TASK_BREAKDOWN, 240, 312);
  gtk_widget_set_size_request (spinbuttonFLOOR_TASK_BREAKDOWN, 60, 27);

  label79 = gtk_label_new (_("STUDENT NUMBER BY FLOOR : "));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed9), label79, 248, 368);
  gtk_widget_set_size_request (label79, 210, 17);

  label77 = gtk_label_new (_("STUDENT NUMBER BY BLOC : "));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed9), label77, 240, 232);
  gtk_widget_set_size_request (label77, 210, 17);

  labelSTUDENT_NUMBER = gtk_label_new ("");
  gtk_widget_show (labelSTUDENT_NUMBER);
  gtk_fixed_put (GTK_FIXED (fixed9), labelSTUDENT_NUMBER, 160, 128);
  gtk_widget_set_size_request (labelSTUDENT_NUMBER, 100, 17);

  labelBLOC_NUMBER = gtk_label_new ("");
  gtk_widget_show (labelBLOC_NUMBER);
  gtk_fixed_put (GTK_FIXED (fixed9), labelBLOC_NUMBER, 248, 272);
  gtk_widget_set_size_request (labelBLOC_NUMBER, 100, 17);

  labelFLOOR_NUMBER = gtk_label_new ("");
  gtk_widget_show (labelFLOOR_NUMBER);
  gtk_fixed_put (GTK_FIXED (fixed9), labelFLOOR_NUMBER, 248, 416);
  gtk_widget_set_size_request (labelFLOOR_NUMBER, 100, 17);

  comboboxentryBLOC_TASK_BREAKDOWN = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryBLOC_TASK_BREAKDOWN);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentryBLOC_TASK_BREAKDOWN, 240, 176);
  gtk_widget_set_size_request (comboboxentryBLOC_TASK_BREAKDOWN, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryBLOC_TASK_BREAKDOWN), _("EXTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryBLOC_TASK_BREAKDOWN), _("EXTERIOR-B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryBLOC_TASK_BREAKDOWN), _("INTERIOR-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryBLOC_TASK_BREAKDOWN), _("INTERIOR-B"));

  label88 = gtk_label_new (_("STUDENT DISPATCHING"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed9), label88, 200, 32);
  gtk_widget_set_size_request (label88, 200, 30);

  label75 = gtk_label_new (_("STUDENT NUMBER : "));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed9), label75, 0, 128);
  gtk_widget_set_size_request (label75, 140, 17);

  buttonSHOW_BLOC = gtk_button_new ();
  gtk_widget_show (buttonSHOW_BLOC);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonSHOW_BLOC, 448, 224);
  gtk_widget_set_size_request (buttonSHOW_BLOC, 100, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_BLOC), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("SHOW "));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox19), label86, FALSE, FALSE, 0);

  buttonSHOW_FLOOR = gtk_button_new ();
  gtk_widget_show (buttonSHOW_FLOOR);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonSHOW_FLOOR, 464, 360);
  gtk_widget_set_size_request (buttonSHOW_FLOOR, 100, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_FLOOR), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("SHOW "));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox18), label85, FALSE, FALSE, 0);

  buttonSHOW_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonSHOW_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonSHOW_STUDENT, 288, 120);
  gtk_widget_set_size_request (buttonSHOW_STUDENT, 100, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_STUDENT), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("SHOW "));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox16), label83, FALSE, FALSE, 0);

  entryCHAMBER_TASK_BREAKDOWN = gtk_entry_new ();
  gtk_widget_show (entryCHAMBER_TASK_BREAKDOWN);
  gtk_fixed_put (GTK_FIXED (fixed9), entryCHAMBER_TASK_BREAKDOWN, 248, 464);
  gtk_widget_set_size_request (entryCHAMBER_TASK_BREAKDOWN, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCHAMBER_TASK_BREAKDOWN), 8226);

  label81 = gtk_label_new (_("STUDENT NUMBER BY CHAMBER :"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed9), label81, 240, 504);
  gtk_widget_set_size_request (label81, 230, 17);

  buttonSHOW_CHAMBER = gtk_button_new ();
  gtk_widget_show (buttonSHOW_CHAMBER);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonSHOW_CHAMBER, 480, 496);
  gtk_widget_set_size_request (buttonSHOW_CHAMBER, 100, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_CHAMBER), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("SHOW "));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox20), label87, FALSE, FALSE, 0);

  labelCHAMBER_NUMBER = gtk_label_new ("");
  gtk_widget_show (labelCHAMBER_NUMBER);
  gtk_fixed_put (GTK_FIXED (fixed9), labelCHAMBER_NUMBER, 256, 552);
  gtk_widget_set_size_request (labelCHAMBER_NUMBER, 100, 17);

  label6 = gtk_label_new (_("TASK BREAKDOWN"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label6);

  label1 = gtk_label_new (_("FOYER AGENT DASHBOARD"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 152, 24);
  gtk_widget_set_size_request (label1, 286, 18);

  g_signal_connect ((gpointer) buttonADD_STUDENT, "clicked",
                    G_CALLBACK (on_buttonADD_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDISPLAY_STUDENT, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonREMOVE_STUDENT, "clicked",
                    G_CALLBACK (on_buttonREMOVE_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_UPDATE, "clicked",
                    G_CALLBACK (on_buttonSHOW_UPDATE_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_START_UPDATING_STUDENT, "clicked",
                    G_CALLBACK (on_button_START_UPDATING_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonFIND, "clicked",
                    G_CALLBACK (on_buttonFIND_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_BLOC, "clicked",
                    G_CALLBACK (on_buttonSHOW_BLOC_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_FLOOR, "clicked",
                    G_CALLBACK (on_buttonSHOW_FLOOR_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_STUDENT, "clicked",
                    G_CALLBACK (on_buttonSHOW_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_CHAMBER, "clicked",
                    G_CALLBACK (on_buttonSHOW_CHAMBER_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (foyer_agent, foyer_agent, "foyer_agent");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (foyer_agent, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryADD_STUDENT_FIRSTNAME, "entryADD_STUDENT_FIRSTNAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryADD_STUDENT_MAIL, "entryADD_STUDENT_MAIL");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryADD_STUDENT_ID, "entryADD_STUDENT_ID");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryADD_STUDENT_LASTNAME, "entryADD_STUDENT_LASTNAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonADD_STUDENT_DAY, "spinbuttonADD_STUDENT_DAY");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonADD_STUDENT_YEAR, "spinbuttonADD_STUDENT_YEAR");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonADD_STUDENT_MONTH, "spinbuttonADD_STUDENT_MONTH");
  GLADE_HOOKUP_OBJECT (foyer_agent, label13, "label13");
  GLADE_HOOKUP_OBJECT (foyer_agent, label10, "label10");
  GLADE_HOOKUP_OBJECT (foyer_agent, label8, "label8");
  GLADE_HOOKUP_OBJECT (foyer_agent, label9, "label9");
  GLADE_HOOKUP_OBJECT (foyer_agent, label11, "label11");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonADD_STUDENT_FLOOR, "spinbuttonADD_STUDENT_FLOOR");
  GLADE_HOOKUP_OBJECT (foyer_agent, label64, "label64");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryADD_STUDENT_CHAMBER, "entryADD_STUDENT_CHAMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, label62, "label62");
  GLADE_HOOKUP_OBJECT (foyer_agent, label12, "label12");
  GLADE_HOOKUP_OBJECT (foyer_agent, label71, "label71");
  GLADE_HOOKUP_OBJECT (foyer_agent, comboboxentryADD_STUDENT_BLOC, "comboboxentryADD_STUDENT_BLOC");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonADD_STUDENT, "buttonADD_STUDENT");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (foyer_agent, image1, "image1");
  GLADE_HOOKUP_OBJECT (foyer_agent, label14, "label14");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonDISPLAY_STUDENT, "buttonDISPLAY_STUDENT");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (foyer_agent, image2, "image2");
  GLADE_HOOKUP_OBJECT (foyer_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelADD_MSG, "labelADD_MSG");
  GLADE_HOOKUP_OBJECT (foyer_agent, label2, "label2");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (foyer_agent, entrySTUDENT_ID, "entrySTUDENT_ID");
  GLADE_HOOKUP_OBJECT (foyer_agent, label18, "label18");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonREMOVE_STUDENT, "buttonREMOVE_STUDENT");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (foyer_agent, image5, "image5");
  GLADE_HOOKUP_OBJECT (foyer_agent, label19, "label19");
  GLADE_HOOKUP_OBJECT (foyer_agent, button1, "button1");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (foyer_agent, image6, "image6");
  GLADE_HOOKUP_OBJECT (foyer_agent, label22, "label22");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelREMOVE_MSG, "labelREMOVE_MSG");
  GLADE_HOOKUP_OBJECT (foyer_agent, label3, "label3");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_ID_UPDATE, "entryUPDATE_ID_UPDATE");
  GLADE_HOOKUP_OBJECT (foyer_agent, label20, "label20");
  GLADE_HOOKUP_OBJECT (foyer_agent, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (foyer_agent, label43, "label43");
  GLADE_HOOKUP_OBJECT (foyer_agent, label44, "label44");
  GLADE_HOOKUP_OBJECT (foyer_agent, label45, "label45");
  GLADE_HOOKUP_OBJECT (foyer_agent, label46, "label46");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_FIRST_NAME, "entryUPDATE_FIRST_NAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_MAIL, "entryUPDATE_MAIL");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_ID, "entryUPDATE_ID");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_LAST_NAME, "entryUPDATE_LAST_NAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonUPDATE_DAY, "spinbuttonUPDATE_DAY");
  GLADE_HOOKUP_OBJECT (foyer_agent, label36, "label36");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonUPDATE_YEAR, "spinbuttonUPDATE_YEAR");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonUPDATE_MONTH, "spinbuttonUPDATE_MONTH");
  GLADE_HOOKUP_OBJECT (foyer_agent, label37, "label37");
  GLADE_HOOKUP_OBJECT (foyer_agent, label41, "label41");
  GLADE_HOOKUP_OBJECT (foyer_agent, label35, "label35");
  GLADE_HOOKUP_OBJECT (foyer_agent, label40, "label40");
  GLADE_HOOKUP_OBJECT (foyer_agent, label34, "label34");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelFIRSTNAME, "labelFIRSTNAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonSHOW_UPDATE, "buttonSHOW_UPDATE");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (foyer_agent, image12, "image12");
  GLADE_HOOKUP_OBJECT (foyer_agent, label42, "label42");
  GLADE_HOOKUP_OBJECT (foyer_agent, label65, "label65");
  GLADE_HOOKUP_OBJECT (foyer_agent, label66, "label66");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonUPDATE_FLOOR, "spinbuttonUPDATE_FLOOR");
  GLADE_HOOKUP_OBJECT (foyer_agent, label72, "label72");
  GLADE_HOOKUP_OBJECT (foyer_agent, label67, "label67");
  GLADE_HOOKUP_OBJECT (foyer_agent, label68, "label68");
  GLADE_HOOKUP_OBJECT (foyer_agent, label73, "label73");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryUPDATE_CHAMBER, "entryUPDATE_CHAMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, label47, "label47");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelFLOOR, "labelFLOOR");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelCHAMBER, "labelCHAMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelMAIL, "labelMAIL");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelBIRTHDAY, "labelBIRTHDAY");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelBLOC, "labelBLOC");
  GLADE_HOOKUP_OBJECT (foyer_agent, comboboxentryUPDATE_BLOC, "comboboxentryUPDATE_BLOC");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelLASTNAME, "labelLASTNAME");
  GLADE_HOOKUP_OBJECT (foyer_agent, button_START_UPDATING_STUDENT, "button_START_UPDATING_STUDENT");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (foyer_agent, image9, "image9");
  GLADE_HOOKUP_OBJECT (foyer_agent, label25, "label25");
  GLADE_HOOKUP_OBJECT (foyer_agent, button2, "button2");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (foyer_agent, image7, "image7");
  GLADE_HOOKUP_OBJECT (foyer_agent, label23, "label23");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelUPDATE_MSG, "labelUPDATE_MSG");
  GLADE_HOOKUP_OBJECT (foyer_agent, label4, "label4");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryFIND_ID, "entryFIND_ID");
  GLADE_HOOKUP_OBJECT (foyer_agent, label52, "label52");
  GLADE_HOOKUP_OBJECT (foyer_agent, label53, "label53");
  GLADE_HOOKUP_OBJECT (foyer_agent, label54, "label54");
  GLADE_HOOKUP_OBJECT (foyer_agent, label51, "label51");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelID1, "labelID1");
  GLADE_HOOKUP_OBJECT (foyer_agent, label48, "label48");
  GLADE_HOOKUP_OBJECT (foyer_agent, label74, "label74");
  GLADE_HOOKUP_OBJECT (foyer_agent, label70, "label70");
  GLADE_HOOKUP_OBJECT (foyer_agent, label69, "label69");
  GLADE_HOOKUP_OBJECT (foyer_agent, label55, "label55");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelBIRTHDAY1, "labelBIRTHDAY1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelMAIL1, "labelMAIL1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelCHAMBER1, "labelCHAMBER1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelLASTNAME1, "labelLASTNAME1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelBLOC1, "labelBLOC1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelFLOOR1, "labelFLOOR1");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelFIRSTNAME1, "labelFIRSTNAME1");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonFIND, "buttonFIND");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (foyer_agent, image15, "image15");
  GLADE_HOOKUP_OBJECT (foyer_agent, label61, "label61");
  GLADE_HOOKUP_OBJECT (foyer_agent, FIND, "FIND");
  GLADE_HOOKUP_OBJECT (foyer_agent, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (foyer_agent, spinbuttonFLOOR_TASK_BREAKDOWN, "spinbuttonFLOOR_TASK_BREAKDOWN");
  GLADE_HOOKUP_OBJECT (foyer_agent, label79, "label79");
  GLADE_HOOKUP_OBJECT (foyer_agent, label77, "label77");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelSTUDENT_NUMBER, "labelSTUDENT_NUMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelBLOC_NUMBER, "labelBLOC_NUMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelFLOOR_NUMBER, "labelFLOOR_NUMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, comboboxentryBLOC_TASK_BREAKDOWN, "comboboxentryBLOC_TASK_BREAKDOWN");
  GLADE_HOOKUP_OBJECT (foyer_agent, label88, "label88");
  GLADE_HOOKUP_OBJECT (foyer_agent, label75, "label75");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonSHOW_BLOC, "buttonSHOW_BLOC");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (foyer_agent, image19, "image19");
  GLADE_HOOKUP_OBJECT (foyer_agent, label86, "label86");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonSHOW_FLOOR, "buttonSHOW_FLOOR");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (foyer_agent, image18, "image18");
  GLADE_HOOKUP_OBJECT (foyer_agent, label85, "label85");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonSHOW_STUDENT, "buttonSHOW_STUDENT");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (foyer_agent, image16, "image16");
  GLADE_HOOKUP_OBJECT (foyer_agent, label83, "label83");
  GLADE_HOOKUP_OBJECT (foyer_agent, entryCHAMBER_TASK_BREAKDOWN, "entryCHAMBER_TASK_BREAKDOWN");
  GLADE_HOOKUP_OBJECT (foyer_agent, label81, "label81");
  GLADE_HOOKUP_OBJECT (foyer_agent, buttonSHOW_CHAMBER, "buttonSHOW_CHAMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (foyer_agent, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (foyer_agent, image20, "image20");
  GLADE_HOOKUP_OBJECT (foyer_agent, label87, "label87");
  GLADE_HOOKUP_OBJECT (foyer_agent, labelCHAMBER_NUMBER, "labelCHAMBER_NUMBER");
  GLADE_HOOKUP_OBJECT (foyer_agent, label6, "label6");
  GLADE_HOOKUP_OBJECT (foyer_agent, label1, "label1");

  return foyer_agent;
}

GtkWidget*
create_TREEVIEW (void)
{
  GtkWidget *TREEVIEW;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *buttonBACK_STUDENT;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label16;
  GtkWidget *buttonREFRESH_STUDENT;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label17;

  TREEVIEW = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (TREEVIEW), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (TREEVIEW), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 53, 80);
  gtk_widget_set_size_request (treeview1, 792, 280);

  buttonBACK_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonBACK_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonBACK_STUDENT, 96, 472);
  gtk_widget_set_size_request (buttonBACK_STUDENT, 110, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonBACK_STUDENT), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("BACK"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox3), label16, FALSE, FALSE, 0);

  buttonREFRESH_STUDENT = gtk_button_new ();
  gtk_widget_show (buttonREFRESH_STUDENT);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonREFRESH_STUDENT, 496, 472);
  gtk_widget_set_size_request (buttonREFRESH_STUDENT, 110, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonREFRESH_STUDENT), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox4), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonBACK_STUDENT, "clicked",
                    G_CALLBACK (on_buttonBACK_STUDENT_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonREFRESH_STUDENT, "clicked",
                    G_CALLBACK (on_buttonREFRESH_STUDENT_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (TREEVIEW, TREEVIEW, "TREEVIEW");
  GLADE_HOOKUP_OBJECT (TREEVIEW, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (TREEVIEW, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (TREEVIEW, buttonBACK_STUDENT, "buttonBACK_STUDENT");
  GLADE_HOOKUP_OBJECT (TREEVIEW, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (TREEVIEW, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (TREEVIEW, image3, "image3");
  GLADE_HOOKUP_OBJECT (TREEVIEW, label16, "label16");
  GLADE_HOOKUP_OBJECT (TREEVIEW, buttonREFRESH_STUDENT, "buttonREFRESH_STUDENT");
  GLADE_HOOKUP_OBJECT (TREEVIEW, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (TREEVIEW, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (TREEVIEW, image4, "image4");
  GLADE_HOOKUP_OBJECT (TREEVIEW, label17, "label17");

  return TREEVIEW;
}

