/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *treeview_afficher;
  GtkWidget *service_plus_reclamer;
  GtkWidget *retour;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label29;
  GtkWidget *button_refresh_reclamation;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label30;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("fenetre afficher"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed2);

  treeview_afficher = gtk_tree_view_new ();
  gtk_widget_show (treeview_afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_afficher, 24, 48);
  gtk_widget_set_size_request (treeview_afficher, 712, 344);

  service_plus_reclamer = gtk_label_new ("");
  gtk_widget_show (service_plus_reclamer);
  gtk_fixed_put (GTK_FIXED (fixed2), service_plus_reclamer, 496, 432);
  gtk_widget_set_size_request (service_plus_reclamer, 192, 32);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed2), retour, 136, 408);
  gtk_widget_set_size_request (retour, 140, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retour), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("BACK"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox9), label29, FALSE, FALSE, 0);

  button_refresh_reclamation = gtk_button_new ();
  gtk_widget_show (button_refresh_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), button_refresh_reclamation, 416, 408);
  gtk_widget_set_size_request (button_refresh_reclamation, 140, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_refresh_reclamation), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox10), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_afficher, "row_activated",
                    G_CALLBACK (on_treeview_afficher_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_refresh_reclamation, "clicked",
                    G_CALLBACK (on_button_refresh_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview_afficher, "treeview_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, service_plus_reclamer, "service_plus_reclamer");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, retour, "retour");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image9, "image9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_refresh_reclamation, "button_refresh_reclamation");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image10, "image10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label30, "label30");

  return fenetre_afficher;
}

GtkWidget*
create_SmartEsprit (void)
{
  GtkWidget *SmartEsprit;
  GtkWidget *fixed3;
  GtkWidget *buttonsign_off_reclamation;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *AddReclamationID;
  GtkWidget *AddReclamationLast;
  GtkWidget *AddReclamationFirst;
  GtkWidget *AddReclamationDescription;
  GtkWidget *AddReclamationDate;
  GtkWidget *First_name;
  GtkWidget *ID;
  GtkWidget *ReclamationLast;
  GtkWidget *ReclamationReclamation;
  GtkWidget *ReclamationDescription;
  GtkWidget *ReclamationDate;
  GtkWidget *msg;
  GtkWidget *msg1;
  GtkWidget *AddReclamationAdd;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label25;
  GtkWidget *AddReclamationDisplay;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label26;
  GtkWidget *comboboxreclamation;
  GtkWidget *label1;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *UpdateReclamationID;
  GtkWidget *UpdateReclamationLast;
  GtkWidget *UpdateReclamationFirst;
  GtkWidget *UpdateReclamationDescription;
  GtkWidget *UpdateReclamationDate;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *UpdateReclamationAdd;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label23;
  GtkWidget *UpdateReclamationDisplay;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label24;
  GtkWidget *comboboxreclamation_update;
  GtkWidget *label2;
  GtkWidget *fixed7;
  GtkWidget *label18;
  GtkWidget *entryID_REMOVE_RECLAMATION;
  GtkWidget *buttonRemove_reclamation;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label27;
  GtkWidget *button2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label28;
  GtkWidget *label3;
  GtkWidget *fixed8;
  GtkWidget *label19;
  GtkWidget *buttoncheck_reclamation;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label20;
  GtkWidget *msg_service;
  GtkWidget *label17;

  SmartEsprit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SmartEsprit), _("Reclamation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (SmartEsprit), fixed3);

  buttonsign_off_reclamation = gtk_button_new ();
  gtk_widget_show (buttonsign_off_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonsign_off_reclamation, 520, 0);
  gtk_widget_set_size_request (buttonsign_off_reclamation, 128, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonsign_off_reclamation), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("SIGN OFF"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox2), label22, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("RECLAMATION DASHBORD"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 160, 24);
  gtk_widget_set_size_request (label21, 297, 41);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 0, 72);
  gtk_widget_set_size_request (notebook1, 648, 536);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  AddReclamationID = gtk_entry_new ();
  gtk_widget_show (AddReclamationID);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationID, 200, 48);
  gtk_widget_set_size_request (AddReclamationID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddReclamationID), 8226);

  AddReclamationLast = gtk_entry_new ();
  gtk_widget_show (AddReclamationLast);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationLast, 200, 88);
  gtk_widget_set_size_request (AddReclamationLast, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddReclamationLast), 8226);

  AddReclamationFirst = gtk_entry_new ();
  gtk_widget_show (AddReclamationFirst);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationFirst, 200, 128);
  gtk_widget_set_size_request (AddReclamationFirst, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddReclamationFirst), 8226);

  AddReclamationDescription = gtk_entry_new ();
  gtk_widget_show (AddReclamationDescription);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationDescription, 200, 208);
  gtk_widget_set_size_request (AddReclamationDescription, 216, 120);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddReclamationDescription), 8226);

  AddReclamationDate = gtk_entry_new ();
  gtk_widget_show (AddReclamationDate);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationDate, 200, 344);
  gtk_widget_set_size_request (AddReclamationDate, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddReclamationDate), 8226);

  First_name = gtk_label_new (_("First name "));
  gtk_widget_show (First_name);
  gtk_fixed_put (GTK_FIXED (fixed4), First_name, 40, 136);
  gtk_widget_set_size_request (First_name, 104, 16);

  ID = gtk_label_new (_("ID"));
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed4), ID, 64, 56);
  gtk_widget_set_size_request (ID, 50, 17);

  ReclamationLast = gtk_label_new (_("Last name"));
  gtk_widget_show (ReclamationLast);
  gtk_fixed_put (GTK_FIXED (fixed4), ReclamationLast, 48, 96);
  gtk_widget_set_size_request (ReclamationLast, 82, 17);

  ReclamationReclamation = gtk_label_new (_("Reclamation"));
  gtk_widget_show (ReclamationReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), ReclamationReclamation, 40, 176);
  gtk_widget_set_size_request (ReclamationReclamation, 96, 16);

  ReclamationDescription = gtk_label_new (_("Description"));
  gtk_widget_show (ReclamationDescription);
  gtk_fixed_put (GTK_FIXED (fixed4), ReclamationDescription, 40, 256);
  gtk_widget_set_size_request (ReclamationDescription, 104, 16);

  ReclamationDate = gtk_label_new (_("Date of reclamation"));
  gtk_widget_show (ReclamationDate);
  gtk_fixed_put (GTK_FIXED (fixed4), ReclamationDate, 24, 352);
  gtk_widget_set_size_request (ReclamationDate, 152, 16);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed4), msg, 56, 392);
  gtk_widget_set_size_request (msg, 439, 17);

  msg1 = gtk_label_new ("");
  gtk_widget_show (msg1);
  gtk_fixed_put (GTK_FIXED (fixed4), msg1, 80, 392);
  gtk_widget_set_size_request (msg1, 376, 16);

  AddReclamationAdd = gtk_button_new ();
  gtk_widget_show (AddReclamationAdd);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationAdd, 128, 424);
  gtk_widget_set_size_request (AddReclamationAdd, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (AddReclamationAdd), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("ADD"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox5), label25, FALSE, FALSE, 0);

  AddReclamationDisplay = gtk_button_new ();
  gtk_widget_show (AddReclamationDisplay);
  gtk_fixed_put (GTK_FIXED (fixed4), AddReclamationDisplay, 328, 424);
  gtk_widget_set_size_request (AddReclamationDisplay, 104, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (AddReclamationDisplay), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox6), label26, FALSE, FALSE, 0);

  comboboxreclamation = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxreclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxreclamation, 200, 168);
  gtk_widget_set_size_request (comboboxreclamation, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation), _("ADMINISTRATION"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation), _("FOYER"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation), _("RESTAURATION"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation), _("SECURITY"));

  label1 = gtk_label_new (_("ADD"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_widget_set_size_request (label1, 150, -1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 0, 0);
  gtk_widget_set_size_request (fixed6, 648, 472);

  UpdateReclamationID = gtk_entry_new ();
  gtk_widget_show (UpdateReclamationID);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationID, 200, 48);
  gtk_widget_set_size_request (UpdateReclamationID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UpdateReclamationID), 8226);

  UpdateReclamationLast = gtk_entry_new ();
  gtk_widget_show (UpdateReclamationLast);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationLast, 200, 88);
  gtk_widget_set_size_request (UpdateReclamationLast, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UpdateReclamationLast), 8226);

  UpdateReclamationFirst = gtk_entry_new ();
  gtk_widget_show (UpdateReclamationFirst);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationFirst, 200, 128);
  gtk_widget_set_size_request (UpdateReclamationFirst, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UpdateReclamationFirst), 8226);

  UpdateReclamationDescription = gtk_entry_new ();
  gtk_widget_show (UpdateReclamationDescription);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationDescription, 200, 208);
  gtk_widget_set_size_request (UpdateReclamationDescription, 216, 120);
  gtk_entry_set_invisible_char (GTK_ENTRY (UpdateReclamationDescription), 8226);

  UpdateReclamationDate = gtk_entry_new ();
  gtk_widget_show (UpdateReclamationDate);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationDate, 200, 344);
  gtk_widget_set_size_request (UpdateReclamationDate, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UpdateReclamationDate), 8226);

  label11 = gtk_label_new (_("Reclamation"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed6), label11, 40, 176);
  gtk_widget_set_size_request (label11, 96, 16);

  label12 = gtk_label_new (_("Date of reclamation"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed6), label12, 24, 352);
  gtk_widget_set_size_request (label12, 152, 16);

  label13 = gtk_label_new (_("First name "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed6), label13, 40, 136);
  gtk_widget_set_size_request (label13, 104, 16);

  label14 = gtk_label_new (_("Last name"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 48, 96);
  gtk_widget_set_size_request (label14, 82, 17);

  label15 = gtk_label_new (_("ID"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 64, 56);
  gtk_widget_set_size_request (label15, 50, 17);

  label16 = gtk_label_new (_("Description"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 40, 256);
  gtk_widget_set_size_request (label16, 104, 16);

  UpdateReclamationAdd = gtk_button_new ();
  gtk_widget_show (UpdateReclamationAdd);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationAdd, 160, 416);
  gtk_widget_set_size_request (UpdateReclamationAdd, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (UpdateReclamationAdd), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("UPDATE"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox3), label23, FALSE, FALSE, 0);

  UpdateReclamationDisplay = gtk_button_new ();
  gtk_widget_show (UpdateReclamationDisplay);
  gtk_fixed_put (GTK_FIXED (fixed6), UpdateReclamationDisplay, 320, 416);
  gtk_widget_set_size_request (UpdateReclamationDisplay, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (UpdateReclamationDisplay), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox4), label24, FALSE, FALSE, 0);

  comboboxreclamation_update = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxreclamation_update);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxreclamation_update, 200, 168);
  gtk_widget_set_size_request (comboboxreclamation_update, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation_update), _("ADMINISTRATION"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation_update), _("FOYER"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation_update), _("RESTAURATION"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxreclamation_update), _("SECURITY"));

  label2 = gtk_label_new (_("UPDATE"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_widget_set_size_request (label2, 150, -1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  label18 = gtk_label_new (_("ID :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed7), label18, 128, 88);
  gtk_widget_set_size_request (label18, 72, 32);

  entryID_REMOVE_RECLAMATION = gtk_entry_new ();
  gtk_widget_show (entryID_REMOVE_RECLAMATION);
  gtk_fixed_put (GTK_FIXED (fixed7), entryID_REMOVE_RECLAMATION, 208, 88);
  gtk_widget_set_size_request (entryID_REMOVE_RECLAMATION, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_REMOVE_RECLAMATION), 8226);

  buttonRemove_reclamation = gtk_button_new ();
  gtk_widget_show (buttonRemove_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonRemove_reclamation, 120, 216);
  gtk_widget_set_size_request (buttonRemove_reclamation, 104, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonRemove_reclamation), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("REMOVE"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox7), label27, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed7), button2, 344, 216);
  gtk_widget_set_size_request (button2, 104, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox8), label28, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("REMOVE"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_widget_set_size_request (label3, 150, -1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  label19 = gtk_label_new (_("THE MOST RECLAMED SERVICE :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed8), label19, 48, 152);
  gtk_widget_set_size_request (label19, 225, 48);

  buttoncheck_reclamation = gtk_button_new ();
  gtk_widget_show (buttoncheck_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed8), buttoncheck_reclamation, 240, 48);
  gtk_widget_set_size_request (buttoncheck_reclamation, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttoncheck_reclamation), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("CHECK"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox1), label20, FALSE, FALSE, 0);

  msg_service = gtk_label_new ("");
  gtk_widget_show (msg_service);
  gtk_fixed_put (GTK_FIXED (fixed8), msg_service, 264, 168);
  gtk_widget_set_size_request (msg_service, 343, 17);

  label17 = gtk_label_new (_("SERVICE"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label17);
  gtk_widget_set_size_request (label17, 150, -1);

  g_signal_connect ((gpointer) buttonsign_off_reclamation, "clicked",
                    G_CALLBACK (on_buttonsign_off_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddReclamationAdd, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddReclamationDisplay, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) UpdateReclamationAdd, "clicked",
                    G_CALLBACK (on_UpdateReclamationAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) UpdateReclamationDisplay, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRemove_reclamation, "clicked",
                    G_CALLBACK (on_buttonRemove_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncheck_reclamation, "clicked",
                    G_CALLBACK (on_buttoncheck_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SmartEsprit, SmartEsprit, "SmartEsprit");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (SmartEsprit, buttonsign_off_reclamation, "buttonsign_off_reclamation");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image2, "image2");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label22, "label22");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label21, "label21");
  GLADE_HOOKUP_OBJECT (SmartEsprit, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationID, "AddReclamationID");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationLast, "AddReclamationLast");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationFirst, "AddReclamationFirst");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationDescription, "AddReclamationDescription");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationDate, "AddReclamationDate");
  GLADE_HOOKUP_OBJECT (SmartEsprit, First_name, "First_name");
  GLADE_HOOKUP_OBJECT (SmartEsprit, ID, "ID");
  GLADE_HOOKUP_OBJECT (SmartEsprit, ReclamationLast, "ReclamationLast");
  GLADE_HOOKUP_OBJECT (SmartEsprit, ReclamationReclamation, "ReclamationReclamation");
  GLADE_HOOKUP_OBJECT (SmartEsprit, ReclamationDescription, "ReclamationDescription");
  GLADE_HOOKUP_OBJECT (SmartEsprit, ReclamationDate, "ReclamationDate");
  GLADE_HOOKUP_OBJECT (SmartEsprit, msg, "msg");
  GLADE_HOOKUP_OBJECT (SmartEsprit, msg1, "msg1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationAdd, "AddReclamationAdd");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image5, "image5");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label25, "label25");
  GLADE_HOOKUP_OBJECT (SmartEsprit, AddReclamationDisplay, "AddReclamationDisplay");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image6, "image6");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label26, "label26");
  GLADE_HOOKUP_OBJECT (SmartEsprit, comboboxreclamation, "comboboxreclamation");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label1, "label1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationID, "UpdateReclamationID");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationLast, "UpdateReclamationLast");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationFirst, "UpdateReclamationFirst");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationDescription, "UpdateReclamationDescription");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationDate, "UpdateReclamationDate");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label11, "label11");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label12, "label12");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label13, "label13");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label14, "label14");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label15, "label15");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label16, "label16");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationAdd, "UpdateReclamationAdd");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image3, "image3");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label23, "label23");
  GLADE_HOOKUP_OBJECT (SmartEsprit, UpdateReclamationDisplay, "UpdateReclamationDisplay");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image4, "image4");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label24, "label24");
  GLADE_HOOKUP_OBJECT (SmartEsprit, comboboxreclamation_update, "comboboxreclamation_update");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label2, "label2");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label18, "label18");
  GLADE_HOOKUP_OBJECT (SmartEsprit, entryID_REMOVE_RECLAMATION, "entryID_REMOVE_RECLAMATION");
  GLADE_HOOKUP_OBJECT (SmartEsprit, buttonRemove_reclamation, "buttonRemove_reclamation");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image7, "image7");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label27, "label27");
  GLADE_HOOKUP_OBJECT (SmartEsprit, button2, "button2");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image8, "image8");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label28, "label28");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label3, "label3");
  GLADE_HOOKUP_OBJECT (SmartEsprit, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label19, "label19");
  GLADE_HOOKUP_OBJECT (SmartEsprit, buttoncheck_reclamation, "buttoncheck_reclamation");
  GLADE_HOOKUP_OBJECT (SmartEsprit, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, image1, "image1");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label20, "label20");
  GLADE_HOOKUP_OBJECT (SmartEsprit, msg_service, "msg_service");
  GLADE_HOOKUP_OBJECT (SmartEsprit, label17, "label17");

  return SmartEsprit;
}

