/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MENU (void)
{
  GtkWidget *MENU;
  GtkWidget *fixed5;
  GtkWidget *label5;
  GtkWidget *notebook1;
  GtkWidget *fixed6;
  GtkWidget *entryNAME_ADD_MENU;
  GtkWidget *entryID_ADD_MENU;
  GtkWidget *entryTRASH_ADD_MENU;
  GtkObject *spinbuttonDAY_ADD_MENU_adj;
  GtkWidget *spinbuttonDAY_ADD_MENU;
  GtkObject *spinbuttonMONTH_ADD_MENU_adj;
  GtkWidget *spinbuttonMONTH_ADD_MENU;
  GtkObject *spinbuttonYEAR_ADD_MENU_adj;
  GtkWidget *spinbuttonYEAR_ADD_MENU;
  GtkWidget *buttonADD_MENU;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label16;
  GtkWidget *buttonDISPLAY_MENU;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label15;
  GtkWidget *TRASH;
  GtkWidget *label14;
  GtkWidget *NAME;
  GtkWidget *label41;
  GtkWidget *msg_add_nut;
  GtkWidget *label6;
  GtkWidget *fixed8;
  GtkWidget *entryID_REMOVE_MENU;
  GtkWidget *label19;
  GtkWidget *button4;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *buttonREMOVE_MENU;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *msg_remove_nut;
  GtkWidget *label7;
  GtkWidget *fixed9;
  GtkWidget *entryNAME_UPDATE_MENU;
  GtkWidget *entryID_UPDATE_MENU;
  GtkWidget *entryTRASH_UPDATE_MENU;
  GtkWidget *NAME_update;
  GtkWidget *TRASH_update;
  GtkObject *spinbuttonUPDATE_DAY_MENU_adj;
  GtkWidget *spinbuttonUPDATE_DAY_MENU;
  GtkObject *spinbuttonUPDATE_MONTH_MENU_adj;
  GtkWidget *spinbuttonUPDATE_MONTH_MENU;
  GtkObject *spinbuttonUPDATE_YEAR_MENU_adj;
  GtkWidget *spinbuttonUPDATE_YEAR_MENU;
  GtkWidget *label40;
  GtkWidget *ID_update;
  GtkWidget *buttonUPDATE_MENU;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label25;
  GtkWidget *button5;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *msg_update_nut;
  GtkWidget *label8;
  GtkWidget *fixed10;
  GtkObject *spinbuttonUPDATE_DAY_adj;
  GtkWidget *spinbuttonUPDATE_DAY;
  GtkWidget *label28;
  GtkObject *spinbuttonUPDATE_MONTH_adj;
  GtkWidget *spinbuttonUPDATE_MONTH;
  GtkObject *spinbuttonUPDATE_YEAR_adj;
  GtkWidget *spinbuttonUPDATE_YEAR;
  GtkWidget *buttonCHECK_NUTRIONIST;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label29;
  GtkWidget *label31;
  GtkWidget *label33;
  GtkWidget *labelMENU_MSG;
  GtkWidget *label9;
  GtkWidget *fixed11;
  GtkWidget *label37;
  GtkWidget *label38BEST_MENU_MSG;
  GtkWidget *buttonSHOW_BEST_MENU;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label39;
  GtkWidget *label10;

  MENU = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MENU), _("window1"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (MENU), fixed5);

  label5 = gtk_label_new (_("MENU DASHBORD"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed5), label5, 144, 32);
  gtk_widget_set_size_request (label5, 228, 17);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed5), notebook1, 0, 64);
  gtk_widget_set_size_request (notebook1, 512, 464);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entryNAME_ADD_MENU = gtk_entry_new ();
  gtk_widget_show (entryNAME_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), entryNAME_ADD_MENU, 160, 56);
  gtk_widget_set_size_request (entryNAME_ADD_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNAME_ADD_MENU), 8226);

  entryID_ADD_MENU = gtk_entry_new ();
  gtk_widget_show (entryID_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), entryID_ADD_MENU, 160, 104);
  gtk_widget_set_size_request (entryID_ADD_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_ADD_MENU), 8226);

  entryTRASH_ADD_MENU = gtk_entry_new ();
  gtk_widget_show (entryTRASH_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), entryTRASH_ADD_MENU, 160, 152);
  gtk_widget_set_size_request (entryTRASH_ADD_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTRASH_ADD_MENU), 8226);

  spinbuttonDAY_ADD_MENU_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonDAY_ADD_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonDAY_ADD_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonDAY_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonDAY_ADD_MENU, 160, 208);
  gtk_widget_set_size_request (spinbuttonDAY_ADD_MENU, 48, 24);

  spinbuttonMONTH_ADD_MENU_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMONTH_ADD_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMONTH_ADD_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonMONTH_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonMONTH_ADD_MENU, 216, 208);
  gtk_widget_set_size_request (spinbuttonMONTH_ADD_MENU, 48, 24);

  spinbuttonYEAR_ADD_MENU_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  spinbuttonYEAR_ADD_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonYEAR_ADD_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonYEAR_ADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonYEAR_ADD_MENU, 272, 208);
  gtk_widget_set_size_request (spinbuttonYEAR_ADD_MENU, 64, 24);

  buttonADD_MENU = gtk_button_new ();
  gtk_widget_show (buttonADD_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonADD_MENU, 104, 296);
  gtk_widget_set_size_request (buttonADD_MENU, 90, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonADD_MENU), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("ADD"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox2), label16, FALSE, FALSE, 0);

  buttonDISPLAY_MENU = gtk_button_new ();
  gtk_widget_show (buttonDISPLAY_MENU);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonDISPLAY_MENU, 288, 296);
  gtk_widget_set_size_request (buttonDISPLAY_MENU, 90, 27);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonDISPLAY_MENU), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox1), label15, FALSE, FALSE, 0);

  TRASH = gtk_label_new (_("TRASH"));
  gtk_widget_show (TRASH);
  gtk_fixed_put (GTK_FIXED (fixed6), TRASH, 80, 152);
  gtk_widget_set_size_request (TRASH, 89, 24);

  label14 = gtk_label_new (_("DATE"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 80, 206);
  gtk_widget_set_size_request (label14, 89, 24);

  NAME = gtk_label_new (_("NAME"));
  gtk_widget_show (NAME);
  gtk_fixed_put (GTK_FIXED (fixed6), NAME, 80, 56);
  gtk_widget_set_size_request (NAME, 89, 24);

  label41 = gtk_label_new (_("ID "));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 104, 112);
  gtk_widget_set_size_request (label41, 49, 17);

  msg_add_nut = gtk_label_new ("");
  gtk_widget_show (msg_add_nut);
  gtk_fixed_put (GTK_FIXED (fixed6), msg_add_nut, 152, 256);
  gtk_widget_set_size_request (msg_add_nut, 300, 17);

  label6 = gtk_label_new (_("ADD"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label6);
  gtk_widget_set_size_request (label6, 90, -1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entryID_REMOVE_MENU = gtk_entry_new ();
  gtk_widget_show (entryID_REMOVE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed8), entryID_REMOVE_MENU, 160, 104);
  gtk_widget_set_size_request (entryID_REMOVE_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_REMOVE_MENU), 8226);

  label19 = gtk_label_new (_("ID"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed8), label19, 80, 104);
  gtk_widget_set_size_request (label19, 89, 24);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed8), button4, 288, 296);
  gtk_widget_set_size_request (button4, 90, 27);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button4), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7), label26, FALSE, FALSE, 0);

  buttonREMOVE_MENU = gtk_button_new ();
  gtk_widget_show (buttonREMOVE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonREMOVE_MENU, 104, 296);
  gtk_widget_set_size_request (buttonREMOVE_MENU, 90, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonREMOVE_MENU), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("REMOVE"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  msg_remove_nut = gtk_label_new ("");
  gtk_widget_show (msg_remove_nut);
  gtk_fixed_put (GTK_FIXED (fixed8), msg_remove_nut, 136, 176);
  gtk_widget_set_size_request (msg_remove_nut, 300, 17);

  label7 = gtk_label_new (_("REMOVE"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label7);
  gtk_widget_set_size_request (label7, 90, -1);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entryNAME_UPDATE_MENU = gtk_entry_new ();
  gtk_widget_show (entryNAME_UPDATE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), entryNAME_UPDATE_MENU, 192, 80);
  gtk_widget_set_size_request (entryNAME_UPDATE_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNAME_UPDATE_MENU), 8226);

  entryID_UPDATE_MENU = gtk_entry_new ();
  gtk_widget_show (entryID_UPDATE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), entryID_UPDATE_MENU, 192, 144);
  gtk_widget_set_size_request (entryID_UPDATE_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID_UPDATE_MENU), 8226);

  entryTRASH_UPDATE_MENU = gtk_entry_new ();
  gtk_widget_show (entryTRASH_UPDATE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), entryTRASH_UPDATE_MENU, 192, 208);
  gtk_widget_set_size_request (entryTRASH_UPDATE_MENU, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTRASH_UPDATE_MENU), 8226);

  NAME_update = gtk_label_new (_("NAME"));
  gtk_widget_show (NAME_update);
  gtk_fixed_put (GTK_FIXED (fixed9), NAME_update, 96, 80);
  gtk_widget_set_size_request (NAME_update, 89, 24);

  TRASH_update = gtk_label_new (_("TRASH"));
  gtk_widget_show (TRASH_update);
  gtk_fixed_put (GTK_FIXED (fixed9), TRASH_update, 104, 208);
  gtk_widget_set_size_request (TRASH_update, 89, 24);

  spinbuttonUPDATE_DAY_MENU_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonUPDATE_DAY_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_DAY_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_DAY_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonUPDATE_DAY_MENU, 192, 248);
  gtk_widget_set_size_request (spinbuttonUPDATE_DAY_MENU, 48, 24);

  spinbuttonUPDATE_MONTH_MENU_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonUPDATE_MONTH_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_MONTH_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_MONTH_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonUPDATE_MONTH_MENU, 248, 248);
  gtk_widget_set_size_request (spinbuttonUPDATE_MONTH_MENU, 48, 24);

  spinbuttonUPDATE_YEAR_MENU_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  spinbuttonUPDATE_YEAR_MENU = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_YEAR_MENU_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_YEAR_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonUPDATE_YEAR_MENU, 304, 248);
  gtk_widget_set_size_request (spinbuttonUPDATE_YEAR_MENU, 64, 24);

  label40 = gtk_label_new (_("DATE"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed9), label40, 104, 248);
  gtk_widget_set_size_request (label40, 89, 24);

  ID_update = gtk_label_new (_("ID"));
  gtk_widget_show (ID_update);
  gtk_fixed_put (GTK_FIXED (fixed9), ID_update, 96, 144);
  gtk_widget_set_size_request (ID_update, 89, 24);

  buttonUPDATE_MENU = gtk_button_new ();
  gtk_widget_show (buttonUPDATE_MENU);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonUPDATE_MENU, 112, 352);
  gtk_widget_set_size_request (buttonUPDATE_MENU, 90, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonUPDATE_MENU), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("UPDATE"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed9), button5, 296, 352);
  gtk_widget_set_size_request (button5, 90, 27);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button5), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  msg_update_nut = gtk_label_new ("");
  gtk_widget_show (msg_update_nut);
  gtk_fixed_put (GTK_FIXED (fixed9), msg_update_nut, 152, 296);
  gtk_widget_set_size_request (msg_update_nut, 300, 17);

  label8 = gtk_label_new (_("UPDATE"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label8);
  gtk_widget_set_size_request (label8, 90, -1);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  spinbuttonUPDATE_DAY_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonUPDATE_DAY = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_DAY_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_DAY);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonUPDATE_DAY, 176, 88);
  gtk_widget_set_size_request (spinbuttonUPDATE_DAY, 48, 24);

  label28 = gtk_label_new (_("DATE"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed10), label28, 88, 88);
  gtk_widget_set_size_request (label28, 89, 24);

  spinbuttonUPDATE_MONTH_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonUPDATE_MONTH = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_MONTH_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_MONTH);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonUPDATE_MONTH, 240, 88);
  gtk_widget_set_size_request (spinbuttonUPDATE_MONTH, 48, 24);

  spinbuttonUPDATE_YEAR_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  spinbuttonUPDATE_YEAR = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonUPDATE_YEAR_adj), 1, 0);
  gtk_widget_show (spinbuttonUPDATE_YEAR);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonUPDATE_YEAR, 304, 88);
  gtk_widget_set_size_request (spinbuttonUPDATE_YEAR, 64, 24);

  buttonCHECK_NUTRIONIST = gtk_button_new ();
  gtk_widget_show (buttonCHECK_NUTRIONIST);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonCHECK_NUTRIONIST, 208, 144);
  gtk_widget_set_size_request (buttonCHECK_NUTRIONIST, 85, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonCHECK_NUTRIONIST), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("CHECK"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox9), label29, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("LAUNCH"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed10), label31, 576, 0);
  gtk_widget_set_size_request (label31, 49, 17);

  label33 = gtk_label_new (_("MENU :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed10), label33, 72, 216);
  gtk_widget_set_size_request (label33, 98, 33);

  labelMENU_MSG = gtk_label_new ("");
  gtk_widget_show (labelMENU_MSG);
  gtk_fixed_put (GTK_FIXED (fixed10), labelMENU_MSG, 168, 224);
  gtk_widget_set_size_request (labelMENU_MSG, 328, 16);

  label9 = gtk_label_new (_("CHECK"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label9);
  gtk_widget_set_size_request (label9, 90, -1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  label37 = gtk_label_new (_("THE BEST MENU : "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed11), label37, 88, 128);
  gtk_widget_set_size_request (label37, 146, 17);

  label38BEST_MENU_MSG = gtk_label_new ("");
  gtk_widget_show (label38BEST_MENU_MSG);
  gtk_fixed_put (GTK_FIXED (fixed11), label38BEST_MENU_MSG, 248, 128);
  gtk_widget_set_size_request (label38BEST_MENU_MSG, 198, 17);

  buttonSHOW_BEST_MENU = gtk_button_new ();
  gtk_widget_show (buttonSHOW_BEST_MENU);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonSHOW_BEST_MENU, 208, 184);
  gtk_widget_set_size_request (buttonSHOW_BEST_MENU, 87, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonSHOW_BEST_MENU), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("SHOW"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox10), label39, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("BEST MENU"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label10);
  gtk_widget_set_size_request (label10, 90, -1);

  g_signal_connect ((gpointer) buttonADD_MENU, "clicked",
                    G_CALLBACK (on_buttonADD_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDISPLAY_MENU, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonREMOVE_MENU, "clicked",
                    G_CALLBACK (on_buttonREMOVE_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonUPDATE_MENU, "clicked",
                    G_CALLBACK (on_buttonUPDATE_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_buttonDISPLAY_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCHECK_NUTRIONIST, "clicked",
                    G_CALLBACK (on_buttonCHECK_NUTRIONIST_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSHOW_BEST_MENU, "clicked",
                    G_CALLBACK (on_buttonSHOW_BEST_MENU_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MENU, MENU, "MENU");
  GLADE_HOOKUP_OBJECT (MENU, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (MENU, label5, "label5");
  GLADE_HOOKUP_OBJECT (MENU, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (MENU, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (MENU, entryNAME_ADD_MENU, "entryNAME_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, entryID_ADD_MENU, "entryID_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, entryTRASH_ADD_MENU, "entryTRASH_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonDAY_ADD_MENU, "spinbuttonDAY_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonMONTH_ADD_MENU, "spinbuttonMONTH_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonYEAR_ADD_MENU, "spinbuttonYEAR_ADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, buttonADD_MENU, "buttonADD_MENU");
  GLADE_HOOKUP_OBJECT (MENU, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (MENU, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (MENU, image2, "image2");
  GLADE_HOOKUP_OBJECT (MENU, label16, "label16");
  GLADE_HOOKUP_OBJECT (MENU, buttonDISPLAY_MENU, "buttonDISPLAY_MENU");
  GLADE_HOOKUP_OBJECT (MENU, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (MENU, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (MENU, image1, "image1");
  GLADE_HOOKUP_OBJECT (MENU, label15, "label15");
  GLADE_HOOKUP_OBJECT (MENU, TRASH, "TRASH");
  GLADE_HOOKUP_OBJECT (MENU, label14, "label14");
  GLADE_HOOKUP_OBJECT (MENU, NAME, "NAME");
  GLADE_HOOKUP_OBJECT (MENU, label41, "label41");
  GLADE_HOOKUP_OBJECT (MENU, msg_add_nut, "msg_add_nut");
  GLADE_HOOKUP_OBJECT (MENU, label6, "label6");
  GLADE_HOOKUP_OBJECT (MENU, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (MENU, entryID_REMOVE_MENU, "entryID_REMOVE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, label19, "label19");
  GLADE_HOOKUP_OBJECT (MENU, button4, "button4");
  GLADE_HOOKUP_OBJECT (MENU, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MENU, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MENU, image7, "image7");
  GLADE_HOOKUP_OBJECT (MENU, label26, "label26");
  GLADE_HOOKUP_OBJECT (MENU, buttonREMOVE_MENU, "buttonREMOVE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MENU, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MENU, image5, "image5");
  GLADE_HOOKUP_OBJECT (MENU, label21, "label21");
  GLADE_HOOKUP_OBJECT (MENU, msg_remove_nut, "msg_remove_nut");
  GLADE_HOOKUP_OBJECT (MENU, label7, "label7");
  GLADE_HOOKUP_OBJECT (MENU, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (MENU, entryNAME_UPDATE_MENU, "entryNAME_UPDATE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, entryID_UPDATE_MENU, "entryID_UPDATE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, entryTRASH_UPDATE_MENU, "entryTRASH_UPDATE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, NAME_update, "NAME_update");
  GLADE_HOOKUP_OBJECT (MENU, TRASH_update, "TRASH_update");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_DAY_MENU, "spinbuttonUPDATE_DAY_MENU");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_MONTH_MENU, "spinbuttonUPDATE_MONTH_MENU");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_YEAR_MENU, "spinbuttonUPDATE_YEAR_MENU");
  GLADE_HOOKUP_OBJECT (MENU, label40, "label40");
  GLADE_HOOKUP_OBJECT (MENU, ID_update, "ID_update");
  GLADE_HOOKUP_OBJECT (MENU, buttonUPDATE_MENU, "buttonUPDATE_MENU");
  GLADE_HOOKUP_OBJECT (MENU, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MENU, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MENU, image6, "image6");
  GLADE_HOOKUP_OBJECT (MENU, label25, "label25");
  GLADE_HOOKUP_OBJECT (MENU, button5, "button5");
  GLADE_HOOKUP_OBJECT (MENU, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MENU, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MENU, image8, "image8");
  GLADE_HOOKUP_OBJECT (MENU, label27, "label27");
  GLADE_HOOKUP_OBJECT (MENU, msg_update_nut, "msg_update_nut");
  GLADE_HOOKUP_OBJECT (MENU, label8, "label8");
  GLADE_HOOKUP_OBJECT (MENU, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_DAY, "spinbuttonUPDATE_DAY");
  GLADE_HOOKUP_OBJECT (MENU, label28, "label28");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_MONTH, "spinbuttonUPDATE_MONTH");
  GLADE_HOOKUP_OBJECT (MENU, spinbuttonUPDATE_YEAR, "spinbuttonUPDATE_YEAR");
  GLADE_HOOKUP_OBJECT (MENU, buttonCHECK_NUTRIONIST, "buttonCHECK_NUTRIONIST");
  GLADE_HOOKUP_OBJECT (MENU, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MENU, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MENU, image9, "image9");
  GLADE_HOOKUP_OBJECT (MENU, label29, "label29");
  GLADE_HOOKUP_OBJECT (MENU, label31, "label31");
  GLADE_HOOKUP_OBJECT (MENU, label33, "label33");
  GLADE_HOOKUP_OBJECT (MENU, labelMENU_MSG, "labelMENU_MSG");
  GLADE_HOOKUP_OBJECT (MENU, label9, "label9");
  GLADE_HOOKUP_OBJECT (MENU, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (MENU, label37, "label37");
  GLADE_HOOKUP_OBJECT (MENU, label38BEST_MENU_MSG, "label38BEST_MENU_MSG");
  GLADE_HOOKUP_OBJECT (MENU, buttonSHOW_BEST_MENU, "buttonSHOW_BEST_MENU");
  GLADE_HOOKUP_OBJECT (MENU, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (MENU, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MENU, image10, "image10");
  GLADE_HOOKUP_OBJECT (MENU, label39, "label39");
  GLADE_HOOKUP_OBJECT (MENU, label10, "label10");

  return MENU;
}

GtkWidget*
create_Display (void)
{
  GtkWidget *Display;
  GtkWidget *fixed7;
  GtkWidget *treeview1;
  GtkWidget *buttonBACK_MENU;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label17;
  GtkWidget *buttonREFRESH_MENU;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label18;

  Display = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Display), _("window2"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Display), fixed7);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 80, 8);
  gtk_widget_set_size_request (treeview1, 376, 216);

  buttonBACK_MENU = gtk_button_new ();
  gtk_widget_show (buttonBACK_MENU);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonBACK_MENU, 48, 264);
  gtk_widget_set_size_request (buttonBACK_MENU, 90, 27);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonBACK_MENU), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("BACK"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox3), label17, FALSE, FALSE, 0);

  buttonREFRESH_MENU = gtk_button_new ();
  gtk_widget_show (buttonREFRESH_MENU);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonREFRESH_MENU, 336, 264);
  gtk_widget_set_size_request (buttonREFRESH_MENU, 90, 27);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonREFRESH_MENU), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("REFRECH"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox4), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonBACK_MENU, "clicked",
                    G_CALLBACK (on_buttonBACK_MENU_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonREFRESH_MENU, "clicked",
                    G_CALLBACK (on_buttonREFRESH_MENU_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Display, Display, "Display");
  GLADE_HOOKUP_OBJECT (Display, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Display, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Display, buttonBACK_MENU, "buttonBACK_MENU");
  GLADE_HOOKUP_OBJECT (Display, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Display, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Display, image3, "image3");
  GLADE_HOOKUP_OBJECT (Display, label17, "label17");
  GLADE_HOOKUP_OBJECT (Display, buttonREFRESH_MENU, "buttonREFRESH_MENU");
  GLADE_HOOKUP_OBJECT (Display, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Display, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Display, image4, "image4");
  GLADE_HOOKUP_OBJECT (Display, label18, "label18");

  return Display;
}

